# Use docker-compose-dev.yml if you want your edits outside the container (pycharm or sublime) to affect
# the working container jupyter notebook and docker runtime

version: "3"
services:
  azure-cis-scanner:
    image: ${AZURE_CIS_SCANNER_IMAGE}
    volumes:
      - ./:/notebooks/azure_cis_scanner          # Development
      - ${ENGAGEMENTS_DIR}:/engagements
      - ${AZURE_CONFIG_DIR}:/home/jovyan/.azure  # if using the apline container then /root/.azure 
      - ${HOST_AZURE_SCANNER_PATH}:/praetorian-tools/azure_cis_scanner  # Development
    ports:
      - ${JUPYTER_PORT}:8888
      - ${FLASK_PORT}:5000
    # To run in production, remove the "--allow-root" and 
    # ensure the last line of the Dockerfile is 
    # USER $NB_UID
    entrypoint: ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
